[build]
  command = "npm install && npx svelte-kit sync && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 